# Generated by Django 5.0.6 on 2026-09-24 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('LIMPIEZA', 'Limpieza'), ('MANTENCION', 'Mantención')], default='DISPONIBLE', max_length=20)),
            ],
            options={
                'verbose_name': 'habitación',
                'verbose_name_plural': 'habitaciones',
                'db_table': 'habitacion',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tipo de habitación',
                'verbose_name_plural': 'tipos de habitación',
                'db_table': 'tipo_habitacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroEstadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huesped', models.CharField(max_length=150)),
                ('llegada', models.DateField()),
                ('salida', models.DateField(blank=True, null=True)),
                ('salida_prevista', models.DateField(blank=True, null=True)),
                ('conflicto', models.BooleanField(default=False)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='rooms.habitacion')),
            ],
            options={
                'verbose_name': 'registro de estadía',
                'verbose_name_plural': 'registros de estadía',
                'db_table': 'registro_estadia',
                'ordering': ['-llegada'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='rooms.tipohabitacion'),
        ),
    ]
