# Generated by Django 5.0.6 on 2026-09-24 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('LIMPIEZA', 'Limpieza'), ('MANTENCION', 'Mantención')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('LIMPIEZA', 'Limpieza'), ('MANTENCION', 'Mantención')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cambios_estado/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado', to=settings.AUTH_USER_MODEL)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='rooms.habitacion')),
            ],
            options={
                'verbose_name': 'cambio de estado de habitación',
                'verbose_name_plural': 'cambios de estado de habitación',
                'db_table': 'cambio_estado_habitacion',
                'ordering': ['-fecha'],
            },
        ),
    ]
