# Generated by Django 5.0.6 on 2026-09-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaFotografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/', verbose_name='imagen')),
                ('subida_en', models.DateTimeField(auto_now_add=True, verbose_name='subida en')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
            ],
            options={
                'verbose_name': 'evidencia fotográfica',
                'verbose_name_plural': 'evidencias fotográficas',
                'db_table': 'evidencia_fotografica',
                'ordering': ['-creada_en'],
            },
        ),
    ]
