# Generated by Django 5.0.6 on 2026-10-04 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoPrivacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('vigente_desde', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'aviso de privacidad',
                'verbose_name_plural': 'avisos de privacidad',
                'db_table': 'aviso_privacidad',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptado_en', models.DateTimeField(auto_now_add=True)),
                ('retirado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('aviso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='privacy.avisoprivacidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to=settings.AUTH_USER_MODEL, verbose_name='titular')),
            ],
            options={
                'verbose_name': 'consentimiento',
                'verbose_name_plural': 'consentimientos',
                'db_table': 'consentimiento',
                'ordering': ['-aceptado_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('recurso', models.CharField(blank=True, default='', max_length=120)),
                ('detalle', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='titular o funcionario')),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'registro_auditoria',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudDerechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACCESO', 'Acceso'), ('RECTIFICACION', 'Rectificación'), ('SUPRESION', 'Supresión'), ('OPOSICION', 'Oposición'), ('PORTABILIDAD', 'Portabilidad'), ('INFORMACION', 'Información')], max_length=20)),
                ('detalle', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('respuesta', models.TextField(blank=True, default='')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_resueltas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_derechos', to=settings.AUTH_USER_MODEL, verbose_name='titular')),
            ],
            options={
                'verbose_name': 'solicitud de derechos del titular',
                'verbose_name_plural': 'solicitudes de derechos del titular',
                'db_table': 'solicitud_derechos',
                'ordering': ['-creada_en'],
            },
        ),
    ]
