# Generated by Django 5.0.6 on 2026-09-24 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('severidad', models.CharField(choices=[('CRITICO', 'Crítico'), ('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], default='MEDIO', max_length=20)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('atendida_en', models.DateTimeField(blank=True, null=True)),
                ('resuelta_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True, default='')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='rooms.habitacion')),
            ],
            options={
                'verbose_name': 'incidencia',
                'verbose_name_plural': 'incidencias',
                'db_table': 'incidencia',
                'ordering': ['-creada_en'],
            },
        ),
    ]
