# Generated by Django 5.0.6 on 2026-09-24 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciontarea',
            name='asignado_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignaciontarea',
            name='habitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='rooms.habitacion'),
        ),
        migrations.AddField(
            model_name='historialestadotarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tasks.asignaciontarea'),
        ),
        migrations.AddField(
            model_name='historialestadotarea',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_tarea', to=settings.AUTH_USER_MODEL),
        ),
    ]
